import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <div className="flex min-h-screen">
        {/* Left Sidebar */}
        <nav className="w-64 p-4 border-r border-gray-200 bg-gray-50">
          <h3 className="mb-4 text-lg font-semibold text-gray-700">
            Rendering Strategies
          </h3>
          <ul className="space-y-2">
            <li>
              <Link 
                href="/" 
                className="text-gray-600 transition-colors hover:text-blue-600"
              >
                Home
              </Link>
            </li>
            <li>
              <Link 
                href="/csr" 
                className="text-gray-600 transition-colors hover:text-blue-600"
              >
                Client-Side Rendering
              </Link>
            </li>
            <li>
              <Link 
                href="/ssr" 
                className="text-gray-600 transition-colors hover:text-blue-600"
              >
                Server-Side Rendering
              </Link>
            </li>
            <li>
              <Link 
                href="/ssg" 
                className="text-gray-600 transition-colors hover:text-blue-600"
              >
                Static Site Generation
              </Link>
            </li>
            <li>
              <Link 
                href="/isr" 
                className="text-gray-600 transition-colors hover:text-blue-600"
              >
                Incremental Static Regeneration
              </Link>
            </li>
          </ul>
        </nav>

        {/* Main Content */}
        <main className="flex-1 p-8 bg-white">
          {children}
        </main>
      </div>
    </body>
  </html>
  );
}
